#!/usr/bin/env bash
# debugging nginx port 80
sudo sed -i 's/listen [::]:80 default_server;/listen [::]:80 default_server ipv6only=off;/' /etc/nginx/sites-available/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo ervice nginx restart 
